### ISSUE TITLE
letterboxd.com CSV importer - przejście z filmweb na letterboxd

### ISSUE THREAD

**Issue by plyr0** [ppatrzyk/filmweb-export#10]
Użyłem filmweb-export, żeby pobrać moje oceny z filmwebu i zaimportować na letterboxd.com
Format csv. Wymagało to usunięcia zbędnych kolumn, oraz zmiany nagłówków:
```
user_rating -> Rating10
original_title -> Title
year -> Year
```
Na 900+ filmów tylko 11 miało problem z identyfikacją po tytule oryginalnym+roku - głównie japońskie i polskie z polskimi znaczkami. Ogólnie działa to świetnie.

Pomysł: żeby dodać do programu taką opcję eksportu csv w formacie letterboxd. I zgłosić filmweb-export jako pół-oficjalny helper script na https://letterboxd.com/about/importing-data/

**Comment by ppatrzyk** [comment]
jest w nowszej wersji, dziękuję za sugestię
