### ISSUE TITLE
ERROR:root:Program error: No ratings count found on website: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by aska-g** [ppatrzyk/filmweb-export#11]
Hej, niezaleznie od uzytych opcji kazdorazowo otrzymuje blad:
```
INFO:root:Checking args...
ERROR:root:Program error: No ratings count found on website: 'NoneType' object has no attribute 'text'
```

Probowalam wkleic cookie zarowno w cudzyslowie i bez, oraz uzyc podstawowej komendy `filmweb <username> <cookie>` oraz komendy z przyklady `filmweb -f all <username> <cookie>`. Czy spotkales sie moze wczesniej z tym problemem?

**Comment by ppatrzyk** [comment]
Cześć @aska-g , uaktualnij proszę do najnowszej wersji (`0.6`). Zobacz https://github.com/ppatrzyk/filmweb-export/issues/8
