### ISSUE TITLE
ERROR:root:Program error: No movies available

### ISSUE THREAD

**Issue by kjurzynski** [ppatrzyk/filmweb-export#15]
Cześć, mam następujący problem - po uruchomieniu skryptu przechodzi mi fetching list of movies 120/120, parsing list of movies 120/120, ale na tym etapie wyskakuje mi error, mówiący że User has 0 movies i taki jak w tytule issue.

Czy byłbyś w stanie mi pomóc w tym? Zainstalowałem dzisiaj, używając po prostu pip install, wersja pythona 3.10.8, także w teorii wszystko powinno chodzić. Windows, jeśli to istotne, używam Terminala.

**Comment by ppatrzyk** [comment]
Cześć @kjurzynski , dziękuję za info. Filmweb zmienił sposób działania strony więc program przestał działać. Zmieniłem co trzeba i wrzuciłem nową wersję (0.9). Zainstaluj proszę i powinno być ok
