### ISSUE TITLE
Eksport zawiera tylko 30 pierwszych filmów 

### ISSUE THREAD

**Issue by ynleborg** [ppatrzyk/filmweb-export#4]
Mam 902 oceny, eksport ma 1110 wierszy ale w kółko powtarza się w nim 30 pierwszych ocen

**Comment by ppatrzyk** [comment]
Witam,

Dziękuję za info. Problem jest następujący: filmweb zmienił system logowania do strony i obecnie [funkcja](https://github.com/ppatrzyk/filmweb-export/blob/master/filmweb/utils.py#L54) nie działa - sesja pozostaje anonimowa. Dlatego wszystkie zapytania są przekierowane na stronę nr 1 (dostępna publicznie), która powtarza się w kółko.

Wrzucili sobie na stronę reCAPTCHA, tak więc POST request na logowanie musi mieć poprawny token w headerze `g-recaptcha-response` ([doc](https://developers.google.com/recaptcha/docs/verify)). Ten jest generowany przez javascript na stronie https://www.filmweb.pl/login . Muszę się zastanowić jak to najłatwiej obejść

**Comment by ppatrzyk** [comment]
naprawione w najnowszej wersji
