### ISSUE TITLE
No ratings count found on website: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by plyr0** [ppatrzyk/filmweb-export#8]
Taki błąd dostaję po uruchomieniu skryptu:
```
INFO:root:Checking args...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.filmweb.pl:443
DEBUG:urllib3.connectionpool:https://www.filmweb.pl:443 "GET /user/plyr0 HTTP/1.1" 200 None
ERROR:root:Program error: No ratings count found on website: 'NoneType' object has no attribute 'text'
```
cookie wygląda inaczej niż w instrukcji:
`didomi_token=; euconsent-v2=; _artuser_prm=; ws_ad=; _fwuser_sessionId=; _fwuser_token=; _fwuser_logged=`

Mam publiczne oceny.

**Comment by ppatrzyk** [comment]
Cześć @plyr0 , dziękuję bardzo za informację. Filmweb zmienił struturę strony od kiedy ostatni raz używałem tego programu, dlatego jest błąd. Muszę zmienić parę rzeczy i wrzucę nową wersję. Dam znać jak będzie naprawione

**Comment by ppatrzyk** [comment]
Po zainstalowaniu najnowszej wersji (`pip3 install --upgrade filmweb`) będzie ok

**Comment by plyr0** [comment]
Potwierdzam, 0.6 działa świetnie(certifi wymagał Pythona 3.10+). Dobra robota, dzięki wielkie, super narzędzie.
